version: '3'
services:
  db:
    container_name: people-demo-db
    image: postgres:14-alpine
    restart: always
    ports:
      - '5402:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: people-demo
